# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  namespace: magistrala
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: 595443389404.dkr.ecr.us-west-2.amazonaws.com/magistrala/http:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8008
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: magistrala
spec:
  selector:
    app: http
  ports:
    - name: http
      port: 8008
      targetPort: http
  type: ClusterIP
