# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora
  namespace: magistrala
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora
  template:
    metadata:
      labels:
        app: lora
    spec:
      containers:
        - name: lora
          image: 595443389404.dkr.ecr.us-west-2.amazonaws.com/lora@sha256:f9f31c9bb955ed0350b459d944c5ad32adb3f7e61a821a3d1d40fd8c2ffe3817
          imagePullPolicy: IfNotPresent
          env:
            - { name: CHIRPSTACK_API_URL, value: "http://chirpstack:8080" }
          ports:
            - name: lora
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: lora
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: lora
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lora
  namespace: magistrala
spec:
  selector:
    app: lora
  ports:
    - name: lora
      port: 8080
      targetPort: lora
  type: ClusterIP
