#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 CHOOVIO Inc.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-adapter
  namespace: magistrala
spec:
  # Keep immutable selector EXACTLY as originally used
  selector:
    matchLabels:
      app.kubernetes.io/name: ws-adapter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ws-adapter
        app.kubernetes.io/component: adapter
        app: ws-adapter                 # extra label ONLY on pod
    spec:
      containers:
        - name: ws-adapter
          image: 595443389404.dkr.ecr.us-west-2.amazonaws.com/ws-adapter@sha256:c021866ee8461b7ed2aa5955cc970948ec63ef83bc5bbd52cbce63b069981fa6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080       # align to platform 8080 standard
          env:
            - name: SMQ_WS_ADAPTER_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_WS_ADAPTER_HTTP_PORT
              value: "8080"
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
      imagePullSecrets: []  # ensure GHCR secret NOT referenced

---
apiVersion: v1
kind: Service
metadata:
  name: ws-adapter
  namespace: magistrala
spec:
  selector:
    app.kubernetes.io/name: ws-adapter
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-adapter
  namespace: magistrala
spec:
  rules:
    - host: sbx.gobee.io
      http:
        paths:
          - path: /api/ws/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ws-adapter
                port:
                  number: 8080
