# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-adapter
  namespace: magistrala
  labels:
    app: ws-adapter
    app.kubernetes.io/name: ws-adapter
    app.kubernetes.io/component: adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-adapter
      app.kubernetes.io/name: ws-adapter
  template:
    metadata:
      labels:
        app: ws-adapter
        app.kubernetes.io/name: ws-adapter
        app.kubernetes.io/component: adapter
    spec:
      containers:
        - name: ws-adapter
          image: "595443389404.dkr.ecr.us-west-2.amazonaws.com/choovio/magistrala/ws-adapter@sha256:1f48a73677e97a8b28f4dd8995ae4ff36092b3e33eee57184e71e3328e21008a"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SMQ_WS_ADAPTER_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_WS_ADAPTER_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ws-adapter
  namespace: magistrala
  labels:
    app: ws-adapter
    app.kubernetes.io/name: ws-adapter
spec:
  selector:
    app: ws-adapter
    app.kubernetes.io/name: ws-adapter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-adapter
  namespace: magistrala
  labels:
    app: ws-adapter
    app.kubernetes.io/name: ws-adapter
spec:
  rules:
    - http:
        paths:
          - path: /api/ws
            pathType: Prefix
            backend:
              service:
                name: ws-adapter
                port:
                  number: 8080
