# SPDX-License-Identifier: Apache-2.0
# Copyright (c) CHOOVIO Inc.# Copyright (c) Abstract Machines
# SPDX-FileCopyrightText: 2025 CHOOVIO Inc.
# SPDX-License-Identifier: MIT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
  namespace: magistrala
  labels:
    app.kubernetes.io/name: ws
    app.kubernetes.io/component: adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ws
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ws
        app.kubernetes.io/component: adapter
    spec:
      containers:
        - name: ws
          image: 595443389404.dkr.ecr.us-west-2.amazonaws.com/ws-adapter@sha256:c021866ee8461b7ed2aa5955cc970948ec63ef83bc5bbd52cbce63b069981fa6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8190
          env:
            - name: SMQ_WS_ADAPTER_HTTP_HOST
              value: "0.0.0.0"
            - name: SMQ_WS_ADAPTER_HTTP_PORT
              value: "8190"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ws
  namespace: magistrala
  labels:
    app.kubernetes.io/name: ws
spec:
  selector:
    app.kubernetes.io/name: ws
  ports:
    - name: http
      port: 8190
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws
  namespace: magistrala
  labels:
    app.kubernetes.io/name: ws
spec:
  rules:
    - http:
        paths:
          - path: /api/ws-adapter
            pathType: Prefix
            backend:
              service:
                name: ws
                port:
                  name: http

