# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
  namespace: magistrala
  labels:
    app: ws
    app.kubernetes.io/name: ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
        app.kubernetes.io/name: ws
    spec:
      containers:
      - name: ws
        image: 595443389404.dkr.ecr.us-west-2.amazonaws.com/ws-adapter@sha256:c021866ee8461b7ed2aa5955cc970948ec63ef83bc5bbd52cbce63b069981fa6
        ports:
        - containerPort: 8186
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8186
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8186
---
apiVersion: v1
kind: Service
metadata:
  name: ws
  namespace: magistrala
  labels:
    app: ws
spec:
  selector:
    app: ws
  ports:
  - name: ws
    port: 8186
    targetPort: 8186
