# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0
name: adapters-ecr

on:
  push:
    branches: [ "main" ]
    paths:
      - "docker/http-adapter/**"
      - "docker/ws-adapter/**"
      - ".github/workflows/adapters-ecr.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "docker/http-adapter/**"
      - "docker/ws-adapter/**"
      - ".github/workflows/adapters-ecr.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-west-2
  ECR_ACCOUNT_ID: 595443389404

jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: adapters-ecr-build
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify required ECR repos exist (no create in CI)
        run: |
          set -euo pipefail
          for name in http-adapter ws-adapter; do
            if ! aws ecr describe-repositories --repository-names "$name" >/dev/null 2>&1; then
              echo "::error::Missing ECR repo: $name. Create it out-of-band, then rerun."
              exit 1
            fi
          done

      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build & push http-adapter
        id: http
        run: |
          set -euo pipefail
          REG="${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          IMAGE="$REG/http-adapter"
          TAG="ci-${GITHUB_SHA::12}"
          docker buildx build \
            --platform linux/amd64 \
            --file docker/http-adapter/Dockerfile \
            --tag "$IMAGE:$TAG" \
            --push \
            .
          DIGEST="$(aws ecr describe-images \
            --repository-name http-adapter \
            --image-ids imageTag="$TAG" \
            --query 'imageDetails[0].imageDigest' --output text)"
          echo "image=$IMAGE@$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Build & push ws-adapter
        id: ws
        run: |
          set -euo pipefail
          REG="${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          IMAGE="$REG/ws-adapter"
          TAG="ci-${GITHUB_SHA::12}"
          docker buildx build \
            --platform linux/amd64 \
            --file docker/ws-adapter/Dockerfile \
            --tag "$IMAGE:$TAG" \
            --push \
            .
          DIGEST="$(aws ecr describe-images \
            --repository-name ws-adapter \
            --image-ids imageTag="$TAG" \
            --query 'imageDetails[0].imageDigest' --output text)"
          echo "image=$IMAGE@$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Emit RESULTS
        shell: bash
        run: |
          esc=$'\033'; orange="${esc}[38;5;214m"; reset="${esc}[0m"
          ts="$(date '+%Y-%m-%d %H:%M:%S %z')"
          {
            echo "==== RESULTS ===="
            echo "Action: BuildAndPushAdapters"
            echo "HttpImage: ${{ steps.http.outputs.image }}"
            echo "WsImage:   ${{ steps.ws.outputs.image }}"
            echo "TIMESTAMP: $ts"
            echo "==== END RESULTS ===="
          } | sed "1s/^/${orange}/;$ s/$/${reset}/"
