# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0
name: adapters-ecr

on:
  push:
    branches: [ "main" ]
    paths:
      - "docker/http-adapter/**"
      - "docker/ws-adapter/**"
      - ".github/workflows/adapters-ecr.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "docker/http-adapter/**"
      - "docker/ws-adapter/**"
      - ".github/workflows/adapters-ecr.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-west-2
  ECR_ACCOUNT_ID: 595443389404

jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: adapters-ecr-build
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify ECR repos exist (no create)
        run: |
          set -euo pipefail
          for name in http-adapter ws-adapter; do
            aws ecr describe-repositories --repository-names "$name" >/dev/null 2>&1 \
              || { echo "::error::Missing ECR repo: $name"; exit 1; }
          done

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Guard: SuperMQ template must exist (we've restored it; fail fast if someone deletes it again)
      - name: Guard SuperMQ template presence
        run: |
          set -euo pipefail
          test -f docker/supermq-docker/templates/users.tmpl || { echo "::error::docker/supermq-docker/templates/users.tmpl missing"; exit 1; }
          head -n 2 docker/supermq-docker/templates/users.tmpl | grep -q 'SPDX-License-Identifier' || { echo "::error::SPDX header missing in users.tmpl"; exit 1; }
          echo "SuperMQ template present with SPDX."

      # Discover mains by scanning files (no module assumptions)
      - name: Discover adapter mains (file scan)
        id: mains
        shell: bash
        run: |
          set -euo pipefail
          # collect directories that contain a main.go with 'package main'
          mapfile -t main_dirs < <(grep -RIl --include='main.go' '^package main$' . | xargs -r -n1 dirname | sort -u)
          printf 'Found main dirs:\n'; printf ' - %s\n' "${main_dirs[@]}" || true

          pick_main() {
            local wantA="$1" wantB="$2"
            # prefer exact suffix match first
            for d in "${main_dirs[@]}"; do [[ "$d" =~ /$wantA$|/$wantB$ ]] && { echo "$d"; return; }; done
            # then prefer dirs containing the token
            for d in "${main_dirs[@]}"; do [[ "$d" =~ $wantA|$wantB ]] && { echo "$d"; return; }; done
            # fallbacks that commonly exist in this repo layout
            [[ -d "./cmd/$wantA" ]] && { echo "./cmd/$wantA"; return; }
            [[ -d "./cmd/$wantB" ]] && { echo "./cmd/$wantB"; return; }
            echo ""
          }

          http_main="$(pick_main http-adapter http)"
          ws_main="$(pick_main ws-adapter ws)"

          echo "HTTP MAIN dir: $http_main"
          echo "WS   MAIN dir: $ws_main"

          if [[ -z "$http_main" || -z "$ws_main" ]]; then
            echo "::error::Could not detect adapter MAIN dirs. http='$http_main' ws='$ws_main'"
            echo "main_dirs candidates were:"; printf ' - %s\n' "${main_dirs[@]}" || true
            exit 1
          fi

          echo "http_main=$http_main" >> "$GITHUB_OUTPUT"
          echo "ws_main=$ws_main"     >> "$GITHUB_OUTPUT"

      - name: Build & push http-adapter
        id: http
        run: |
          set -euo pipefail
          REG="${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          IMAGE="$REG/http-adapter"
          TAG="ci-${GITHUB_SHA::12}"

          docker buildx build \
            --platform linux/amd64 \
            --file docker/http-adapter/Dockerfile \
            --build-arg MAIN='${{ steps.mains.outputs.http_main }}' \
            --tag "$IMAGE:$TAG" \
            --push \
            .

          DIGEST="$(aws ecr describe-images \
            --repository-name http-adapter \
            --image-ids imageTag="$TAG" \
            --query 'imageDetails[0].imageDigest' --output text)"
          echo "image=$IMAGE@$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Build & push ws-adapter
        id: ws
        run: |
          set -euo pipefail
          REG="${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          IMAGE="$REG/ws-adapter"
          TAG="ci-${GITHUB_SHA::12}"

          docker buildx build \
            --platform linux/amd64 \
            --file docker/ws-adapter/Dockerfile \
            --build-arg MAIN='${{ steps.mains.outputs.ws_main }}' \
            --tag "$IMAGE:$TAG" \
            --push \
            .

          DIGEST="$(aws ecr describe-images \
            --repository-name ws-adapter \
            --image-ids imageTag="$TAG" \
            --query 'imageDetails[0].imageDigest' --output text)"
          echo "image=$IMAGE@$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Emit RESULTS
        shell: bash
        run: |
          esc=$'\033'; orange="${esc}[38;5;214m"; reset="${esc}[0m"
          ts="$(date '+%Y-%m-%d %H:%M:%S %z')"
          {
            echo "==== RESULTS ===="
            echo "Action: BuildAndPushAdapters"
            echo "HttpImage: ${{ steps.http.outputs.image }}"
            echo "WsImage:   ${{ steps.ws.outputs.image }}"
            echo "TIMESTAMP: $ts"
            echo "==== END RESULTS ===="
          } | sed "1s/^/${orange}/;$ s/$/${reset}/"
