# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0
name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  checks: write

concurrency:
  group: adapters-${{ github.ref }}
  cancel-in-progress: false

jobs:
  supermq-patches-guard:
    name: SuperMQ patches-only guard (diff vs base)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Block direct edits under docker/supermq-docker
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
          else
            BASE_BRANCH="$(git remote show origin | awk '/HEAD branch/ {print $NF}')"
            BASE_REF="origin/${BASE_BRANCH}"
          fi
          git fetch origin +refs/heads/*:refs/remotes/origin/* >/dev/null 2>&1 || true
          CHANGED=$(git diff --name-only "$BASE_REF"...HEAD -- docker/supermq-docker | grep -v '^docker/supermq-docker/patches/' || true)
          if [[ -n "$CHANGED" ]]; then
            echo "::error::Direct edits in docker/supermq-docker detected (use patches/ only):"
            echo "$CHANGED"; exit 1
          fi
          echo "SuperMQ patches-only policy respected."

  discover-build-contexts:
    name: Discover Docker build contexts
    runs-on: ubuntu-latest
    needs: supermq-patches-guard
    outputs:
      matrix: ${{ steps.ctx.outputs.matrix }}
      count:  ${{ steps.ctx.outputs.count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Discover adapter contexts (bash; one-line outputs)
        id: ctx
        shell: bash
        run: |
          set -euo pipefail
          enc() { jq -Rsc @json; }  # not used but handy
          find_main() {
            local needle="$1"
            # candidates: .../cmd/<name>, .../<name>, .../services/<name>
            mapfile -t CANDIDATES < <(git ls-files | grep -E "/(cmd/)?${needle}(/|$)|(^|/)${needle}(/|$)|/services/${needle}(/|$)" | xargs -r -I{} dirname {} | sort -u)
            for d in "${CANDIDATES[@]}"; do
              if [[ -f "$d/main.go" ]] || grep -q 'package main' "$d"/*.go 2>/dev/null; then
                echo "$d"; return 0
              fi
            done
            echo ""
          }
          includes='[]'
          http_main="$(find_main 'http-adapter')"
          ws_main="$(find_main 'ws-adapter')"

          if [[ -f docker/http-adapter/Dockerfile && -n "$http_main" ]]; then
            includes="$(jq -c --arg m "$http_main" '. + [{"name":"http-adapter","context":".","dockerfile":"docker/http-adapter/Dockerfile","main":$m}]' <<<"$includes")"
          fi
          if [[ -f docker/ws-adapter/Dockerfile && -n "$ws_main" ]]; then
            includes="$(jq -c --arg m "$ws_main" '. + [{"name":"ws-adapter","context":".","dockerfile":"docker/ws-adapter/Dockerfile","main":$m}]' <<<"$includes")"
          fi

          matrix="$(jq -cn --argjson inc "$includes" '{include:$inc}')"
          printf 'matrix=%s\n' "$matrix" >> "$GITHUB_OUTPUT"
          printf 'count=%s\n' "$(jq -r '.include|length' <<<"$matrix")" >> "$GITHUB_OUTPUT"
          echo "$matrix" | jq .

  build-adapters:
    name: Build adapters (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: discover-build-contexts
    if: ${{ needs.discover-build-contexts.outputs.count != '0' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover-build-contexts.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (push only on main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build adapters
        uses: docker/build-push-action@v6
        with:
          context:   ${{ matrix.context }}
          file:      ${{ matrix.dockerfile }}
          build-args: |
            MAIN=${{ matrix.main }}
          platforms: linux/amd64
          push:      ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags:      ghcr.io/choovio/${{ matrix.name }}:${{ github.sha }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to:   type=gha,mode=max
