# SPDX-FileCopyrightText: 2025 CHOOVIO Inc.
# SPDX-License-Identifier: MIT

name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # <-- required to push to GHCR with GITHUB_TOKEN

    env:
      REGISTRY: ghcr.io
      ORG: ${{ github.repository_owner }}
      IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/magistrala
      # If your Makefile expects SERVICES, set it here; otherwise remove this line.
      SERVICES: bootstrap provision re postgres-writer postgres-reader timescale-writer timescale-reader cli alarms reports

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags for the build
        run: |
          git fetch --prune --unshallow --tags || true

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache-dependency-path: "go.sum"

      - name: Run tests
        run: |
          make test

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage/*.out
          verbose: true

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (via GITHUB_TOKEN)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push Dockers
        env:
          REGISTRY: ${{ env.REGISTRY }}
          ORG: ${{ env.ORG }}
          IMAGE_PREFIX: ${{ env.IMAGE_PREFIX }}
          SERVICES: ${{ env.SERVICES }}
        run: |
          # Ensure Makefile picks up our vars; remove SERVICES if your Makefile does not use it.
          export REGISTRY ORG IMAGE_PREFIX SERVICES
          make latest -j "$(nproc)"

      # NOTE: The old repository-dispatch to 'absmach/amdm' has been removed on purpose.
      # If/when you have your OWN deployment repo, add a new dispatch step here that targets YOUR repo.
