# Copyright (c) CHOOVIO Inc.
# SPDX-License-Identifier: Apache-2.0

name: Check License Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check License Header
        run: |
          missing_files=()
          while IFS= read -r file; do
            header="$(head -n 5 "$file")"

            if ! printf '%s' "$header" | grep -Fq "# Copyright (c) CHOOVIO Inc."; then
              missing_files+=("$file")
              continue
            fi

            if ! printf '%s' "$header" | grep -Fq "# SPDX-License-Identifier: Apache-2.0"; then
              missing_files+=("$file")
              continue
            fi
          done < <(grep -rl --exclude-dir={.git,build,**vernemq**,coverage} \
            --exclude=\*.{crt,key,pem,zed,hcl,md,json,csv,mod,sum,tmpl,args} \
            --exclude={CODEOWNERS,LICENSE,MAINTAINERS,enabled_plugins,rabbitmq.conf} \
            .)

          if [ "${#missing_files[@]}" -gt 0 ]; then
            echo "License header check failed"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          fi

          echo "All files have the correct license header!"
