# SPDX-License-Identifier: Apache-2.0
# Copyright (c) CHOOVIO Inc.
name: ECR Build / LoRa
on:
  workflow_dispatch:
  push:
    paths:
      - 'adapters/lora/**'
      - '.github/workflows/build-lora.yml'
  workflow_call:
permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: 595443389404
  ECR_REPO: lora
jobs:
  build:
    uses: ./.github/workflows/build-lora.yml
    secrets: inherit
