# SPDX-License-Identifier: Apache-2.0
# Copyright (c) CHOOVIO Inc.
name: ECR Build / LoRa
on:
  workflow_dispatch:
  push:
    paths:
      - 'adapters/lora/**'
      - '.github/workflows/build-lora.yml'
      - '.github/workflows/ecr-build-lora.yml'
permissions:
  contents: read
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/build-lora.yml
    secrets: inherit
