# SPDX-FileCopyrightText: 2025 CHOOVIO Inc.
# SPDX-License-Identifier: MIT
---
name: SBX Manifest Guard

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate SBX pins exist
        shell: bash
        run: |
          set -euo pipefail
          test -f overrides/sbx-pins.lock.yaml || { echo "Missing overrides/sbx-pins.lock.yaml"; exit 1; }
          echo "OK: overrides/sbx-pins.lock.yaml present"