# SPDX-FileCopyrightText: 2025 CHOOVIO Inc.
# SPDX-License-Identifier: MIT
---
name: SBX Manifest Guard

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check SBX pins file (warn if missing)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f overrides/sbx-pins.lock.yaml ]; then
            echo "OK: overrides/sbx-pins.lock.yaml present"
          else
            echo "WARN: overrides/sbx-pins.lock.yaml not found (non-blocking)"
          fi